// src/pages/DocumentLibrary.jsx — Document Library (Legora theme, matches Campaigns layout)
import { useState, useEffect, useCallback } from 'react'
import { useOutletContext } from 'react-router-dom'
import { supabase } from '@/lib/supabase'
import T from '@/lib/theme'
import TemplateEditorModal from '@/components/TemplateEditorModal'
import { ChevronRight, Download, X, Lock, Users } from 'lucide-react'

const CATEGORY_LABELS = {
  team_deck: 'Team Deck', contract: 'Contract', marketing: 'Marketing',
  legal: 'Legal', financial: 'Financial', agency_agreement: 'Agency Agreement', general: 'General',
  pitch_deck: 'Pitch Deck', proposal: 'Proposal', nda: 'NDA', agreement: 'Agreement',
  brief: 'Meeting Brief', report: 'Campaign Report', other: 'Other',
}

function formatSize(b) {
  if (!b) return '—'
  if (b < 1024) return b + ' B'
  if (b < 1048576) return (b / 1024).toFixed(0) + ' KB'
  return (b / 1048576).toFixed(1) + ' MB'
}

function formatDate(d) {
  if (!d) return '—'
  return new Date(d).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })
}

export default function DocumentLibrary() {
  const { isMobile } = useOutletContext() || {}
  const [docs, setDocs] = useState([])
  const [loading, setLoading] = useState(true)
  const [userRole, setUserRole] = useState('user')
  const [selectedSport, setSelectedSport] = useState(null)
  const [selectedTeam, setSelectedTeam] = useState(null)
  const [selectedType, setSelectedType] = useState(null)
  const [selectedDoc, setSelectedDoc] = useState(null)
  const [searchQuery, setSearchQuery] = useState('')
  const [showTemplateEditor, setShowTemplateEditor] = useState(false)
  const [templates, setTemplates] = useState([])
  const [editingTemplate, setEditingTemplate] = useState(null)
  const [templateForm, setTemplateForm] = useState({ name: '', doc_type: 'other', description: '', output_format: 'pdf', field_schema: [] })
  const [expandedSports, setExpandedSports] = useState({})

  const C = T
  const isSuperAdmin = userRole === 'super_admin'

  useEffect(() => {
    async function load() {
      setLoading(true)
      const { data: { session } } = await supabase.auth.getSession()
      if (session?.user?.email) {
        const { data: cfg } = await supabase.from('kiko_user_config').select('role').eq('email', session.user.email).single()
        if (cfg?.role) setUserRole(cfg.role)
      }
      const { data } = await supabase.from('documents').select('*').order('created_at', { ascending: false })
      // Also load AI-generated documents from kiko_documents
      const { data: kikoDocs } = await supabase.from('kiko_documents').select('*').order('created_at', { ascending: false })
      const normalizedKikoDocs = (kikoDocs || []).map(d => ({
        ...d, title: d.name, file_name: d.name, category: d.doc_type,
        summary: d.description || `Generated by ${d.generated_by === 'kiko' ? 'Kiko AI' : 'user'}`,
        access_level: 'workspace', sport: null, team_name: null,
        _source: 'kiko'
      }))
      setDocs([...(data || []), ...normalizedKikoDocs])
      setLoading(false)
    }
    load()
  }, [])

  useEffect(() => {
    supabase.from('kiko_doc_templates').select('*').order('name').then(({ data }) => setTemplates(data || []))
  }, [showTemplateEditor])

  const saveTemplate = async () => {
    const { name, doc_type, description, output_format, field_schema } = templateForm
    if (!name) return
    if (editingTemplate) {
      await supabase.from('kiko_doc_templates').update({ name, doc_type, description, output_format, field_schema, updated_at: new Date().toISOString() }).eq('id', editingTemplate.id)
    } else {
      await supabase.from('kiko_doc_templates').insert({ name, doc_type, description, output_format, field_schema })
    }
    setShowTemplateEditor(false); setEditingTemplate(null); setTemplateForm({ name: '', doc_type: 'other', description: '', output_format: 'pdf', field_schema: [] })
    supabase.from('kiko_doc_templates').select('*').order('name').then(({ data }) => setTemplates(data || []))
  }

  const deleteTemplate = async (id) => {
    if (!window.confirm('Delete this template?')) return
    await supabase.from('kiko_doc_templates').delete().eq('id', id)
    setTemplates(prev => prev.filter(t => t.id !== id))
  }

  // Filter docs by access level
  const visibleDocs = docs.filter(d => {
    if (!isSuperAdmin) {
      // Regular users only see 'workspace' and 'all_users' docs
      if (d.access_level === 'super_admin_only' || d.access_level === 'private') return false
    }
    if (searchQuery) {
      const q = searchQuery.toLowerCase()
      return [d.title, d.name, d.file_name, d.team_name, d.sport, d.summary, d.category].some(f => (f || '').toLowerCase().includes(q))
    }
    return true
  })

  // Build hierarchical tree: Sport → Team → Docs
  const sportTree = {}
  const typeTree = {}
  visibleDocs.forEach(doc => {
    const sport = doc.sport || null
    const team = doc.team_name || null
    const cat = doc.category || 'general'
    if (sport) {
      if (!sportTree[sport]) sportTree[sport] = { teams: {}, docs: [] }
      if (team) {
        if (!sportTree[sport].teams[team]) sportTree[sport].teams[team] = []
        sportTree[sport].teams[team].push(doc)
      } else {
        sportTree[sport].docs.push(doc)
      }
    }
    if (!typeTree[cat]) typeTree[cat] = []
    typeTree[cat].push(doc)
  })

  // Current docs based on selection
  const getCurrentDocs = () => {
    if (searchQuery) return visibleDocs
    if (selectedTeam && selectedSport) return sportTree[selectedSport]?.teams[selectedTeam] || []
    if (selectedSport) {
      const s = sportTree[selectedSport]
      if (!s) return []
      return [...s.docs, ...Object.values(s.teams).flat()]
    }
    if (selectedType) return typeTree[selectedType] || []
    return visibleDocs
  }
  const currentDocs = getCurrentDocs()

  const currentLabel = selectedTeam || selectedSport || (selectedType ? (CATEGORY_LABELS[selectedType] || selectedType) : 'All documents')

  const toggleSportExpand = (sport) => {
    setExpandedSports(prev => ({ ...prev, [sport]: !prev[sport] }))
  }

  if (loading) return (
    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: 'calc(100vh - 56px)', fontFamily: C.font, color: C.textTertiary }}>Loading documents...</div>
  )

  const cell = { padding: '12px 14px', fontSize: 12, color: C.text, borderBottom: `0.5px solid ${C.border}`, verticalAlign: 'middle' }
  const headerCell = { ...cell, fontSize: 10, textTransform: 'uppercase', letterSpacing: '0.06em', color: C.textTertiary, fontWeight: 500, background: '#F5F4F1', position: 'sticky', top: 0, zIndex: 1, textAlign: 'left' }

  return (
    <div style={{ display: 'flex', height: 'calc(100vh - 56px)', fontFamily: C.font, color: C.text, background: C.bg }}>

      {/* ─── LEFT RAIL ─── */}
      {(!isMobile || (!selectedSport && !selectedType)) && (
        <aside style={{ width: isMobile ? '100%' : 280, flexShrink: 0, borderRight: isMobile ? 'none' : `1px solid ${C.border}`, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
          <div style={{ padding: '18px 18px 12px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <div>
              <div style={{ fontSize: 14, fontWeight: 500, color: C.text }}>Document Library</div>
              <div style={{ fontSize: 11, color: C.textTertiary, marginTop: 2 }}>{visibleDocs.length} document{visibleDocs.length !== 1 ? 's' : ''}</div>
            </div>
            <button onClick={() => setShowTemplateEditor(true)} style={{ padding: "5px 10px", borderRadius: 6, background: "rgba(0,0,0,0.04)", border: "1px solid rgba(0,0,0,0.08)", fontSize: 11, color: "#6B6B6B", cursor: "pointer" }}>Templates</button>
          </div>

          <div style={{ padding: '0 12px 8px' }}>
            <input type="text" placeholder="Search documents..." value={searchQuery} onChange={e => { setSearchQuery(e.target.value); setSelectedSport(null); setSelectedTeam(null); setSelectedType(null) }}
              style={{ width: '100%', padding: '8px 12px', borderRadius: 6, background: 'rgba(0,0,0,0.03)', border: `1px solid ${C.border}`, fontSize: 12, fontFamily: C.font, outline: 'none', color: C.text, boxSizing: 'border-box' }} />
          </div>

          <div style={{ flex: 1, overflowY: 'auto', padding: '0 8px 12px' }}>
            {/* All documents */}
            <button onClick={() => { setSelectedSport(null); setSelectedTeam(null); setSelectedType(null); setSearchQuery('') }}
              style={{ display: 'flex', alignItems: 'center', gap: 8, width: '100%', textAlign: 'left', padding: '10px 12px', marginBottom: 2, borderRadius: 6, border: 'none', background: !selectedSport && !selectedType ? 'rgba(0,0,0,0.06)' : 'transparent', cursor: 'pointer', fontFamily: C.font, fontSize: 13, color: !selectedSport && !selectedType ? C.text : C.textSecondary, fontWeight: !selectedSport && !selectedType ? 500 : 400 }}>
              <span style={{ width: 6, height: 6, borderRadius: '50%', background: !selectedSport && !selectedType ? C.text : C.textTertiary }} />
              All documents
              <span style={{ marginLeft: 'auto', fontSize: 10, color: C.textTertiary }}>{visibleDocs.length}</span>
            </button>

            {/* By sport — expandable with teams */}
            <div style={{ fontSize: 10, textTransform: 'uppercase', letterSpacing: '0.06em', color: C.textTertiary, fontWeight: 500, padding: '14px 12px 6px' }}>By sport</div>
            {Object.entries(sportTree).sort().map(([sport, data]) => {
              const teamCount = Object.keys(data.teams).length
              const totalDocs = data.docs.length + Object.values(data.teams).flat().length
              const isExpanded = expandedSports[sport]
              const isSelected = selectedSport === sport && !selectedTeam
              return (
                <div key={sport}>
                  <button onClick={() => { 
                    if (teamCount > 0) toggleSportExpand(sport)
                    setSelectedSport(sport); setSelectedTeam(null); setSelectedType(null) 
                  }}
                    style={{ display: 'flex', alignItems: 'center', gap: 8, width: '100%', textAlign: 'left', padding: '10px 12px', marginBottom: 1, borderRadius: 6, border: 'none', background: isSelected ? 'rgba(0,0,0,0.06)' : 'transparent', cursor: 'pointer', fontFamily: C.font, fontSize: 13, color: isSelected ? C.text : C.textSecondary, fontWeight: isSelected ? 500 : 400 }}>
                    {teamCount > 0 && (
                      <ChevronRight size={12} style={{ transform: isExpanded ? 'rotate(90deg)' : 'none', transition: 'transform 0.15s', flexShrink: 0, color: C.textTertiary }} />
                    )}
                    {teamCount === 0 && <span style={{ width: 6, height: 6, borderRadius: '50%', background: isSelected ? C.text : C.textTertiary, flexShrink: 0 }} />}
                    {sport}
                    <span style={{ marginLeft: 'auto', fontSize: 10, color: C.textTertiary }}>{totalDocs}</span>
                  </button>
                  {/* Team sub-items */}
                  {isExpanded && Object.entries(data.teams).sort().map(([team, teamDocs]) => {
                    const isTeamSelected = selectedSport === sport && selectedTeam === team
                    return (
                      <button key={team} onClick={() => { setSelectedSport(sport); setSelectedTeam(team); setSelectedType(null) }}
                        style={{ display: 'flex', alignItems: 'center', gap: 8, width: '100%', textAlign: 'left', padding: '8px 12px 8px 32px', marginBottom: 1, borderRadius: 6, border: 'none', background: isTeamSelected ? 'rgba(0,0,0,0.06)' : 'transparent', cursor: 'pointer', fontFamily: C.font, fontSize: 12, color: isTeamSelected ? C.text : C.textTertiary, fontWeight: isTeamSelected ? 500 : 400 }}>
                        <span style={{ width: 5, height: 5, borderRadius: '50%', background: isTeamSelected ? C.text : 'rgba(0,0,0,0.12)', flexShrink: 0 }} />
                        {team}
                        <span style={{ marginLeft: 'auto', fontSize: 10, color: C.textTertiary }}>{teamDocs.length}</span>
                      </button>
                    )
                  })}
                </div>
              )
            })}

            {/* By type */}
            <div style={{ fontSize: 10, textTransform: 'uppercase', letterSpacing: '0.06em', color: C.textTertiary, fontWeight: 500, padding: '14px 12px 6px' }}>By type</div>
            {Object.entries(typeTree).sort().map(([cat, catDocs]) => {
              const isSelected = selectedType === cat
              return (
                <button key={cat} onClick={() => { setSelectedType(isSelected ? null : cat); setSelectedSport(null); setSelectedTeam(null) }}
                  style={{ display: 'flex', alignItems: 'center', gap: 8, width: '100%', textAlign: 'left', padding: '10px 12px', marginBottom: 2, borderRadius: 6, border: 'none', background: isSelected ? 'rgba(0,0,0,0.06)' : 'transparent', cursor: 'pointer', fontFamily: C.font, fontSize: 13, color: isSelected ? C.text : C.textSecondary, fontWeight: isSelected ? 500 : 400 }}>
                  <span style={{ width: 6, height: 6, borderRadius: '50%', background: isSelected ? C.text : C.textTertiary, flexShrink: 0 }} />
                  {CATEGORY_LABELS[cat] || cat}
                  <span style={{ marginLeft: 'auto', fontSize: 10, color: C.textTertiary }}>{catDocs.length}</span>
                </button>
              )
            })}
          </div>
        </aside>
      )}

      {/* ─── MAIN ─── */}
      {(!isMobile || selectedSport || selectedType) && (
        <main style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', minWidth: 0 }}>
          <div style={{ padding: '18px 20px 12px', display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', borderBottom: `0.5px solid ${C.border}` }}>
            <div>
              {isMobile && (
                <button onClick={() => { setSelectedSport(null); setSelectedTeam(null); setSelectedType(null) }} style={{ background: 'none', border: 'none', fontSize: 12, color: C.textSecondary, cursor: 'pointer', fontFamily: C.font, padding: 0, marginBottom: 4 }}>← Back</button>
              )}
              <div style={{ fontSize: 16, fontWeight: 500, color: C.text }}>{currentLabel}</div>
              <div style={{ fontSize: 11, color: C.textTertiary, marginTop: 2 }}>{currentDocs.length} document{currentDocs.length !== 1 ? 's' : ''}</div>
            </div>
            {isSuperAdmin && <div style={{ fontSize: 10, color: '#7d8a64', background: 'rgba(125,138,100,0.08)', padding: '3px 10px', borderRadius: 6, fontWeight: 500 }}>Super Admin</div>}
          </div>

          <div style={{ flex: 1, overflowY: 'auto' }}>
            {currentDocs.length === 0 ? (
              <div style={{ padding: 40, textAlign: 'center', color: C.textTertiary, fontSize: 13 }}>
                {docs.length === 0 ? 'No documents yet — — upload files via Kiko to get started.' : 'No documents in this folder.'}
              </div>
            ) : (
              <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                <thead>
                  <tr>
                    <th style={headerCell}>Name</th>
                    <th style={{ ...headerCell, width: 100 }}>Type</th>
                    {!isMobile && <th style={{ ...headerCell, width: 110 }}>Team</th>}
                    <th style={{ ...headerCell, width: 80 }}>Size</th>
                    <th style={{ ...headerCell, width: 80 }}>Updated</th>
                    <th style={{ ...headerCell, width: 100 }}>Access</th>
                  </tr>
                </thead>
                <tbody>
                  {currentDocs.map(doc => (
                    <tr key={doc.id} onClick={() => setSelectedDoc(doc)} style={{ cursor: 'pointer', transition: 'background 0.1s' }}
                      onMouseOver={e => e.currentTarget.style.background = 'rgba(0,0,0,0.02)'}
                      onMouseOut={e => e.currentTarget.style.background = 'transparent'}>
                      <td style={{ ...cell, fontWeight: 500 }}>{doc.title || doc.name || doc.file_name || 'Document'}</td>
                      <td style={cell}>
                        <span style={{ fontSize: 9, padding: '2px 7px', borderRadius: 4, fontWeight: 500, textTransform: 'uppercase', letterSpacing: '0.04em', background: 'rgba(0,0,0,0.04)', color: C.textSecondary, border: `1px solid ${C.border}` }}>
                          {CATEGORY_LABELS[doc.category] || doc.category || '—'}
                        </span>
                      </td>
                      {!isMobile && <td style={cell}>{doc.team_name || '—'}</td>}
                      <td style={{ ...cell, color: C.textTertiary }}>{formatSize(doc.file_size)}</td>
                      <td style={{ ...cell, color: C.textTertiary }}>{formatDate(doc.updated_at || doc.created_at)}</td>
                      <td style={cell}>
                        {(doc.access_level === 'super_admin_only' || doc.access_level === 'private') ? (
                          <span style={{ fontSize: 9, padding: '2px 7px', borderRadius: 4, fontWeight: 500, textTransform: 'uppercase', letterSpacing: '0.04em', background: 'rgba(184,100,62,0.08)', color: '#B8643E', border: '1px solid rgba(184,100,62,0.15)', display: 'inline-flex', alignItems: 'center', gap: 3 }}>
                            <Lock size={8} /> Super Admin
                          </span>
                        ) : (
                          <span style={{ fontSize: 9, padding: '2px 7px', borderRadius: 4, fontWeight: 500, textTransform: 'uppercase', letterSpacing: '0.04em', background: 'rgba(125,138,100,0.08)', color: '#7d8a64', border: '1px solid rgba(125,138,100,0.15)', display: 'inline-flex', alignItems: 'center', gap: 3 }}>
                            <Users size={8} /> All Users
                          </span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </main>
      )}

      {/* Detail overlay */}
      {selectedDoc && (
        <div style={{ position: 'fixed', inset: 0, zIndex: 300, background: 'rgba(0,0,0,0.4)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20 }}
          onClick={() => setSelectedDoc(null)}>
          <div onClick={e => e.stopPropagation()} style={{ background: C.bg, borderRadius: C.radiusCard, maxWidth: 480, width: '100%', maxHeight: '80vh', overflow: 'auto', padding: 24, boxShadow: C.glassShadowFloat }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 }}>
              <div style={{ fontSize: 18, fontWeight: 500, color: C.text, fontFamily: C.font }}>{selectedDoc.title || selectedDoc.name || 'Document'}</div>
              <button onClick={() => setSelectedDoc(null)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: C.textTertiary, padding: 4 }}><X size={18} /></button>
            </div>
            {selectedDoc.summary && <p style={{ fontSize: 13, color: C.textSecondary, lineHeight: 1.6, margin: '0 0 16px' }}>{selectedDoc.summary}</p>}
            {selectedDoc.kiko_analysis && <p style={{ fontSize: 12, color: C.textTertiary, lineHeight: 1.5, margin: '0 0 16px', padding: 12, background: 'rgba(0,0,0,0.02)', borderRadius: 8 }}>{selectedDoc.kiko_analysis}</p>}
            <div style={{ fontSize: 12, color: C.textTertiary, marginBottom: 16, display: 'grid', gridTemplateColumns: '100px 1fr', gap: '6px 12px' }}>
              {selectedDoc.category && <><span>Type</span><span style={{ color: C.textSecondary }}>{CATEGORY_LABELS[selectedDoc.category] || selectedDoc.category}</span></>}
              {selectedDoc.sport && <><span>Sport</span><span style={{ color: C.textSecondary }}>{selectedDoc.sport}</span></>}
              {selectedDoc.team_name && <><span>Team</span><span style={{ color: C.textSecondary }}>{selectedDoc.team_name}</span></>}
              <span>Size</span><span style={{ color: C.textSecondary }}>{formatSize(selectedDoc.file_size)}</span>
              <span>Uploaded</span><span style={{ color: C.textSecondary }}>{formatDate(selectedDoc.created_at)}</span>
              {selectedDoc.uploaded_by && <><span>By</span><span style={{ color: C.textSecondary }}>{selectedDoc.uploaded_by}</span></>}
              <span>Access</span><span style={{ color: C.textSecondary }}>{selectedDoc.access_level === 'super_admin_only' ? 'Super Admin only' : 'All users'}</span>
            </div>
            <div style={{ display: 'flex', gap: 8 }}>
              {(selectedDoc.file_url || selectedDoc.storage_path) && (
                <a href={selectedDoc.file_url || selectedDoc.storage_path} target="_blank" rel="noopener noreferrer"
                  style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '8px 16px', borderRadius: 6, background: C.text, color: '#FEFEFC', textDecoration: 'none', fontSize: 12, fontWeight: 500, fontFamily: C.font }}>
                  <Download size={14} /> Download
                </a>
              )}
              <button onClick={() => setSelectedDoc(null)}
                style={{ padding: '8px 16px', borderRadius: 6, background: 'transparent', border: `1px solid ${C.border}`, fontSize: 12, color: C.textSecondary, cursor: 'pointer', fontFamily: C.font }}>
                Close
              </button>
            </div>
          </div>
        </div>
      )}
      {showTemplateEditor && <TemplateEditorModal onClose={() => setShowTemplateEditor(false)} />}
    </div>
  )
}
